name: First WorkFlow
on: workflow_dispatch
jobs: 
   first-job:
    runs-on: macos-latest
    steps: 
      - name: Print Geeting
        run: echo "Hello World!"
      - name: Print Good Bye
        run: echo "Done- Bye"
